---
title: "Scrape & Download - Cannabis Retail Data"
author: "Martin Frigaard"
date: "current version: `r Sys.Date()`"
output: github_document
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
require(tidyverse)
library(plotly)
require(janitor)
require(skimr)
library(mosaic)
library(inspectdf)
library(visdat)
library(DT)
# base options ----
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
  scipen = 100000000,
  max.print = 999999
)
# knitr chunk options ----
knitr::opts_chunk$set(
  echo = TRUE, # show/hide all code
  # results = "hide", # hide results
  tidy = FALSE, # cleaner code printing
  comment = "#> ", # better console printing
  eval = TRUE, # turn this to FALSE stop code chunks from running
  message = TRUE, # show messages
  fig.width = 7, # figure width
  fig.height = 5, # figure height
  warning = FALSE, # show warnings
  size = "small", # size of the text
  fig.path = "figs/"
) # location of files
# knitr knit settings ----
knitr::opts_knit$set(
  width = 78
)
```


## Cannabis web data

Resources: [Web Scraping Product Data in R with rvest and purrr](https://www.business-science.io/code-tools/2019/10/07/rvest-web-scraping.html)

This document covers how to scrape the `dutchie` website using R. 

## The website

Scrape this website: [dutchie: Order Marijuana Online for Delivery or Pickup](https://dutchie.com/store/nectar-gresham/menu?)

### 1) Check `robots.txt` 

This is available here:

`https://www.specialized.com/us/en/robots.txt`

`https://dutchie.com/us/en/robots.txt`

### 2) Packages 

```{r packages, message=FALSE, warning=FALSE}
# Load libraries
library(rvest)     # HTML Hacking & Web Scraping
library(jsonlite)  # JSON manipulation
library(tidyverse) # Data Manipulation
library(tidyquant) # ggplot2 theme
library(xopen)     # Opens URL in Browser
library(knitr)     # Pretty HTML Tables
```

```{r}
# URL to View All Bikes
url <- "https://www.specialized.com/us/en/shop/bikes/c/bikes?q=%3Aprice-desc%3Aarchived%3Afalse&show=All" 
# Read HTML from URL 
html <- read_html(url)
html %>%
    html_nodes(".product-list__item-wrapper")

# Store JSON as object
json <- html %>% 
    html_nodes(".product-list__item-wrapper") %>% 
    html_attr("data-product-ic")

# Show the 1st JSON element (1st bike of 399 bikes)
json[1]
```

