---
title: "CanDash (v0.0.6)"
author: "Martin Frigaard"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Contact", href: "https://martinfrigaard.io/" }
    orientation: rows
    social: menu
    css: style.css
runtime: shiny
---

```{r setup, include=FALSE}
# packages ------
library(flexdashboard)
library(shiny)
library(tidyverse)
library(magrittr)
library(plotly)
library(highcharter)
library(viridisLite)
library(treemap)
library(RColorBrewer)
library(ggthemes)
library(magrittr)
# fs::dir_ls("data/processed/", regexp = "2020-06-27")
# import MonthlyLocationSales ------
MonthlyLocationSales <- read_rds("data/processed/2020-06-27-MonthlyLocationSales.rds")
# import ProdCatTop10 ------
ProdCatTop10 <- read_rds("data/processed/2020-06-27-ProdCatTop10.rds")
# import Top10Brands ------
Top10Brands <- read_rds("data/processed/2020-06-27-Top10Brands.rds")
# load the data into the dashboard 
# import WeekOverWeek ------
WeekOverWeek <- readr::read_rds("data/processed/2020-06-27-WeekOverWeek.rds")
WeekOverWeek <- WeekOverWeek %>% 
  # make sure this is all positive!
  dplyr::mutate(week_qty = abs(week_qty)) %>%
  # remove missing
  tidyr::drop_na()
# import GroupedCanData ------
GroupedCanData <- read_rds("data/processed/2020-06-27-GroupedCanData.rds")
# import Top25Data ----
Top25Data <- read_rds("data/processed/2020-06-27-Top25Data.rds")
```

Column {.sidebar}
-----------------------------------------------------------------------

This is a sample sales dashboard for cannabis products. 

**The Data**

These data have been simulated from the [Kushy cannabis data sets](https://github.com/kushyapp/cannabis-dataset). 

Select a year below to view the sales across a 12-month period

```{r select-year}
shiny::selectInput(inputId = "yearNum", 
                   label = h3("Year"), 
    choices = list("2018" = 2018, "2019" = 2019), 
    selected = 1)
```


Select a quarter below to view the sales across a three-month period

```{r selector-quarter}
shiny::selectInput(inputId = "quarterNum", 
                   label = h3("Fiscal Quarter"), 
    choices = list("Q1" = 1, "Q2" = 2, "Q3" = 3, "Q4" = 4), 
    selected = 3)
```

Select a region to view track the median purchase order amount by location

```{r selector-location}
shiny::selectInput(inputId = "locationNum", 
                   label = h3("Sales Region"), 
                   choices = list("West/Pacific" = 1, 
                                  "West/Mountain" = 2), 
                   selected = 1)
```


**The Dashboard**

This dashboard was built using [`flexdashboard`](https://rmarkdown.rstudio.com/flexdashboard/), interactive dashboards written in [Rmarkdown](https://rmarkdown.rstudio.com/) and [Shiny](https://shiny.rstudio.com/).

**The Graphics**

The line graphs were built using [`ggplot2`](https://ggplot2.tidyverse.org/) and [`plotly`](https://github.com/ropensci/plotly#readme), with theme components from [`hrbrthemes`](https://hrbrmstr.github.io/hrbrthemes/). 

Zoom in on particular with click and drag (read more [here](https://plotly.com/chart-studio-help/zoom-pan-hover-controls/)).

The `treemap` was built with [`highcharter`](http://jkunst.com/highcharter/).

***Quantity sold per week***

This graph displays the overall quantity sold per week (with a 'best fit' line and shaded confidence interval)

***Week over week sales***

Percentage increase in sales by quarter and month

***Median Order Amount by Location***

Median order amount per week in each State/Region

***Daily Sales by Category***

This [treemap](https://en.wikipedia.org/wiki/Treemapping) displays the largest selling cannabis product categories per day

***Best Selling Product Categories***

A column chart for the best performing product categories per month

***Best Selling Brands***

A column chart for the best performing brands per month

Row {.tabset .tabset-fade}
-------------------------------------

### Quantity sold per week

```{r quantity-sold-per-week, eval=TRUE}
# # set theme for wow ----
ggplot2::theme_set(hrbrthemes::theme_ipsum_rc(
  base_family = "Ubuntu",
  base_size = 9,
  strip_text_size = 11,
  axis_title_size = 9,
  plot_title_size = 15,
  subtitle_size = 13
))

# create reactive for quarter ----
WowReact <- reactive({
  # rename this reactive to generic data
        data <- WeekOverWeek %>%
                # filter year
                dplyr::filter(invoice_year == as.numeric(input$yearNum))
          # return data
          data
        
    })

# create labs for Quantity Per Week ----
labs_quantity_per_week <- ggplot2::labs(
         x = "Week", 
         y = "Quantity Sold",
         title = "Quantity Per Week") 

# render plot with reactive -----
plotly::renderPlotly({
  
   data <- WowReact()
   
    gg_qpw <- ggplot2::ggplot(data = data, 
                  # put week_year on the x
               aes(x = week_year, 
                   # and week quantity on the y
                   y = week_qty)) + 
      # add the line plot
        ggplot2::geom_line() +
      # add the smooth (predictor)
        ggplot2::geom_smooth() +
      # add points
        ggplot2::geom_point() +
      # add labels
        labs_quantity_per_week
    
    plotly::toWebGL(plotly::ggplotly(gg_qpw))
})
```


### Week over week sales 

```{r wow-plot}
# labels Week Over Week Annual Sales ----
labs_wow_annual_sales <- ggplot2::labs(
  y = 'Sales', 
  x = ' ', 
  title = 'Week Over Week Annual Sales',
  subtitle = "Simulated Cannabis Sales Data by Quarter",
  caption = "Graphic and analysis by PDG") 

# create reactive (QDataReact) for quarter data ----
QDataReact <- reactive({
  # rename this reactive to generic data
          # filter this to the selected option from the side-panel
         data <- WeekOverWeek %>% 
              # limit range of dates
              filter(invoice_year == as.numeric(input$yearNum) & 
                             quar == as.numeric(input$quarterNum)) %>% 
                        
              # remove missing 
              tidyr::drop_na()
         
         data
    })

# create session data
cdata <- session$clientData


# render plot with reactive -----
plotly::renderPlotly({
  
   data <- QDataReact()
   
   gg_wow_sales <- data %>% 
  
   # this will put week_year on the x
    ggplot2::ggplot(aes(x = week_year, 
                        # and the week over week quantity on the y
                        y = wow_quantity,
                        # group by month
                        group = month)) +
  # add the line plot
    ggplot2::geom_line(color = "green4",
                       alpha = 0.3,
                       show.legend = FALSE) +
  # and the point
    ggplot2::geom_point(color = "green4", 
                        alpha = 0.7,
                           show.legend = FALSE) +
  # the axis title here will inherit the size and color
    ggplot2::theme(axis.title = element_text(face = c("bold"))) +
  # this will remove the legend
    ggplot2::theme(legend.title = element_blank()) +
  # this adds the percent on the y axis
    ggplot2::scale_y_continuous(labels = 
                                  scales::percent_format(accuracy = 1)) +
  # # here we facet by the month
    ggplot2::facet_wrap(. ~ month,
                        #
                        scales = "free") +
    ggplot2::theme(axis.text.x = 
                     element_text(angle = 45, 
                                  hjust = 0.5, 
                                  vjust = 0.5)) +
           # add theme
    ggthemes::theme_hc(base_size = 10, 
                                   base_family = "Ubuntu") +
    
  labs_wow_annual_sales
   
   # convert to plotly object
    plotly::hide_legend(
      plotly::toWebGL(
        plotly::ggplotly(p = gg_wow_sales, 
                         
                       width = cdata$output_pid_width, 
                       
                       height = cdata$output_pid_height)
        ))
  
})
```

### Median Order Amount By Location 

```{r ggTop100MonthlyLocationSales}
# labels
labs_median_order_value <- ggplot2::labs(
                  y = 'Median Order Amount', 
                  x = ' ',
                  title = 'Median Monthly Order Amount by Location')

# create reactive (MonLocSalesReac) for Location data ----
MonLocSalesReac <- reactive({
  # rename this reactive to generic data
         data <- MonthlyLocationSales %>%
                  # sort these by total_monthly_sales
                  dplyr::arrange(desc(tot_mnth_sale_loc)) %>% 
                  # select category for location
                  dplyr::filter(sales_reg_num == input$locationNum & 
                                  # select category for quarter
                                invoice_year == as.numeric(input$yearNum))
         data
    })


# render plot with reactive -----
plotly::renderPlotly({

    MonLocSalesReac() %>%
    # plot
    ggplot2::ggplot(data = ., 
                    # put months on the x 
           mapping = aes(x = floor_month, 
                         # median monthly sales
                         y = med_mnth_sale_loc)) +
    # add the line
    ggplot2::geom_line(color = "green4", show.legend = FALSE) +
    # add the point
    ggplot2::geom_point(color = "green4", show.legend = FALSE) +
    # add the y format
    ggplot2::scale_y_continuous(labels = 
                                    scales::dollar_format(accuracy = 1)) +
  
    # facet this by the location and set scales to free
    ggplot2::facet_wrap(sales_region ~ location, 
                        scales = "free_x") + 
  
      # adjust the x axis text
    ggplot2::theme(axis.text.x = 
                     element_text(angle = 45, 
                                  hjust = 0.5, 
                                  vjust = 0.5)) +
  # add the labels
  labs_median_order_value -> ggMedianOrderValue

# convert to plotly
plotly::hide_legend(
  plotly::toWebGL(
    plotly::ggplotly(ggMedianOrderValue)))
})
```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Daily Sales by Category

```{r treemap}
# treemap --------
highcharter::hctreemap2(GroupedCanData, 
                        
              group_vars = c("product_category"),
              
              size_var = "units_by_prod_cat", 
              
              color_var = "units_by_prod_cat",
              
              layoutAlgorithm = "squarified",
              
              levelIsConstant = FALSE,
              
              allowDrillToNode = TRUE) %>% 
  
    # add the RColorBrewer greens 
  
    hc_colorAxis(minColor = RColorBrewer::brewer.pal(7, "Greens")[1],
                 
                 maxColor = RColorBrewer::brewer.pal(7, "Greens")[7]) 

```

### Best Selling Categories

```{r geom-col-top-10-brand-categories}
# define labels ----
top_10product_labs <- ggplot2::labs(x = "Product Categories",
                             
                  y = "Count",
                  
                  title = "Top 10 Cannabis Products")

# create session data
cdata <- session$clientData
  
# create BrandCatTop10React reactive ----

ProdCatTop10React <- reactive({
  
  # rename this reactive to generic data
  
        data <- ProdCatTop10
        
          data
        
})

# render plot with reactive -----
plotly::renderPlotly({
  
  data <- ProdCatTop10React()
  
    data %>% 
      
    ggplot2::ggplot(aes(x = product_category, 
                        
                      y = n)) +
  
    ggplot2::geom_col(aes(fill = product_category), 
                      
                      show.legend = FALSE) +

    ggplot2::coord_flip() +
    
    ggplot2::scale_fill_viridis_d(direction = -1) +
    
    top_10product_labs -> gg_top10_product_categories
    
    # convert to plotly object
    plotly::hide_legend(plotly::toWebGL(
      
      plotly::ggplotly(p = gg_top10_product_categories)))
    
    
})
```

### Best Selling Brands

```{r geom-col-top-10-brands}
# define labels ----
top_10brand_labs <- ggplot2::labs(x = " ",
                             
                  y = "Count (Per Month)",
                  
                  title = "Top 10 Cannabis Brands") 

# create session data
cdata <- session$clientData
  
# create Top10React reactive ----

Top10React <- reactive({
  
  # rename this reactive to generic data
  
        data <- Top10Brands
        
          data
        
})

# render plot with reactive -----
plotly::renderPlotly({
  
  data <- Top10React()
  
    data %>% 
      
    ggplot2::ggplot(aes(x = brand_name, 
                      y = n)) +
  
    ggplot2::geom_col(aes(fill = brand_name), 
                      show.legend = FALSE) +
  

    ggplot2::coord_flip() + 
      
    ggplot2::theme_minimal(base_size = 10, 
                               
                               base_family = "Ubuntu") +
      
    ggplot2::scale_fill_viridis_d(direction = -1) +
      
    top_10brand_labs -> gg_top10_brands
    
    
    
    # convert to plotly object
plotly::hide_legend(plotly::toWebGL(
  
      plotly::ggplotly(p = gg_top10_brands)))
    
})
```

