---
title: "CanDash (a minimal cannabis dashboard)"
author: "Martin Frigaard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
# packages ------
library(flexdashboard)
library(shiny)
library(tidyverse)
library(magrittr)
# fs::dir_tree("data/processed/")
# load the data into the dashboard
CanData <- readr::read_csv("data/processed/2020-03-19-CannabisWowData.csv")
Top50Data <- readr::read_csv("data/processed/2020-03-21-Top50Data.csv")
MonLocSales <- readr::read_csv("data/processed/2020-03-19-MonthlyLocationSales.csv")
WeekOverWeek <- readr::read_csv("data/processed/2020-03-19-WeekOverWeek.csv")

Q3Data <- WeekOverWeek %>% 
  tidyr::drop_na() %>% 
  dplyr::filter(.data = ., month %in% c("Apr", "May", "Jun")) 
```

Inputs {.sidebar}
-----------------------------------------------------------------------

This is a sample sales dashboard for cannabis products. 

Column {data-width=600}
-----------------------------------------------------------------------

### Quantity sold per week

```{r quantity-sold-per-week, eval=TRUE}
# create reactive
WowReact <- reactive({
  # rename this reactive to generic data
        data <- WeekOverWeek
        
          
          data <- tidyr::drop_na(data = data)
          
          data
        
    })

labs_quantity_per_week <- ggplot2::labs(
         x = "Week", 
         y = "Quantity Sold",
         title = "Quantity Per Week") 

# render plot with reactive -----
renderPlot({
  
   data <- WowReact()
   
    ggplot2::ggplot(data = data, 
               aes(x = week_year, 
                   # and week quantity on the y
                   y = week_qty)) + 
      # add the line plot
        ggplot2::geom_line() +
      # add the smooth (predictor)
        ggplot2::geom_smooth() +
      # add points
        ggplot2::geom_point() +
      # add labels
        labs_quantity_per_week
})
```


### Week over week sales 

```{r wow-plot}
# set theme
ggplot2::theme_set(hrbrthemes::theme_ipsum_rc(
  base_size = 10,
  strip_text_size = 11,
  axis_title_size = 9,
  plot_title_size = 15,
  subtitle_size = 13
))
# create reactive
Q3DataReact <- reactive({
  # rename this reactive to generic data
        data <- Q3Data
        
    })
  # these are the labels
labs_wow_annual_sales <- ggplot2::labs(
  y = 'Sales', 
  x = 'Week', 
  title = 'Week Over Week Annual Sales',
  subtitle = "Quarter 3 Simulated Cannabis Sales Data",
  caption = "Graphic and analysis by PDG") 


# render plot with reactive -----
renderPlot({
  
   data <- Q3DataReact()
   
   data %>% 
  
  # this will put week_year on the x
    ggplot2::ggplot(aes(x = week_year, 
                        # and the week over week quantity on the y
                        y = wow_quantity)) +
  # add the line plot
    ggplot2::geom_line() +
  # and the point
    ggplot2::geom_point() +
  # the axis title here will inherit the size and color
    ggplot2::theme(axis.title = element_text(face = c("bold"))) +
  # this will remove the legend
    ggplot2::theme(legend.title = element_blank()) +
  # this adds the percent on the y axis
    ggplot2::scale_y_continuous(labels = 
                                  scales::percent_format(accuracy = 1),) +
  # here we facet by the month
    ggplot2::facet_wrap(. ~ month, 
                        # 
                        scales = "free") + 
    ggplot2::theme(axis.text.x = 
                     element_text(angle = 45, 
                                  hjust = 0.5, 
                                  vjust = 0.5)) +
  labs_wow_annual_sales
})
```


Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r treemap}
library(highcharter)
library(viridisLite)
library(treemap)
# set the theme for highcharter --------
thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Ubuntu")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )
# grouped cannabis data --------
GroupedCanData <- CanData %>%
  dplyr::group_by(brand_category, quantity) %>% 
  dplyr::summarise(sales_by_cat = n()) %>% 
  dplyr::ungroup() %>% 
  dplyr::sample_n(100)
# GroupedCanData

# treemap --------
highcharter::hctreemap2(GroupedCanData, 
              group_vars = c("brand_category"),
              size_var = "sales_by_cat", 
              color_var = "sales_by_cat",
              layoutAlgorithm = "squarified",
              levelIsConstant = FALSE,
              allowDrillToNode = TRUE,
              palette = rev(viridis(6))) %>% 
  highcharter::hc_add_theme(thm)
```

### Best Sellers

```{r top-50-brands-categories}
# create reactive
Top50React <- reactive({
  # rename this reactive to generic data
        data <- Top50Data
        
          data
        
    })

# render plot with reactive -----
renderPlot({
  
  data <- Top50React()
  
    data %>% 
      
    ggplot2::ggplot(aes(x = brand, 
                      
                      y = brand_cat_count, 
                      
                      group = brand_category)) +
      
    ggplot2::geom_col(aes(fill = brand), 
                      
                      show.legend = FALSE) +
      
    ggplot2::labs(x = "Brands",
                  
                  y = "Count",
                  
                  title = "Top 50 Cannabis Brands & Categories") +
      
    ggplot2::coord_flip() +
      
    facet_wrap(. ~ brand_category, 
               
               scales = "free")
})
```
