---
title: "Sales Report with Highcharter"
author: "Joshua Kunst"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(highcharter)
library(dplyr)
library(viridisLite)
library(forecast)
library(treemap)
library(flexdashboard)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Ubuntu")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )

```

Column {data-width=600}
-----------------------------------------------------------------------

### Sales Forecast

```{r sales-forcast}
AirPassengers <- datasets::AirPassengers
AirPassengers %>% 
    # level = Confidence level for prediction intervals, 
    forecast::forecast(level = 90) %>% 
    # draw a particular plot for an object of a particular class in a single 
    # command. This needs to be a ts object
    highcharter::hchart() %>% 
    # Add highcharts themes to a highchart object.
    highcharter::hc_add_theme(thm)
```

### Sales by State

```{r usmap}
# get data for the map
data("USArrests", package = "datasets")
# get the map
data("usgeojson", package = "highcharter")

# create some rownames from the states
USArrests <- USArrests %>%
  mutate(state = rownames(.))
# str(USArrests)
# dplyr::glimpse(USArrests)

n <- 4
colstops <- data.frame(
  q = 0:n/n, 
  c = base::substring(text = viridisLite::viridis(n = n + 1), 
                      first =  0, 
                      last = 7)) 
# colstops
#      q       c
# 1 0.00 #440154
# 2 0.25 #3B528B
# 3 0.50 #21908C
# 4 0.75 #5DC863
# 5 1.00 #FDE725

colstops <- colstops %>%
  # similar to rlist::list.parse but this removes names
  highcharter::list_parse2()


highcharter::highchart() %>%
  # series map
  highcharter::hc_add_series_map(hc = ., 
                                 # map as a list in geojson format
                                 map = usgeojson, 
                                 # us arrests
                                 df = USArrests, 
                                 # 
                                 name = "Sales",
                                 # from data frame
                                 value = "Murder",
                                 
                    joinBy = c("woename", "state"),
                    
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Sales by Category

```{r treemap}
data("Groceries", 
     package = "arules")
dfitems <- dplyr::tbl_df(Groceries@itemInfo)

set.seed(10)

dfitemsg <- dfitems %>%
  dplyr::mutate(category = gsub(" ", "-", level1),
                subcategory = gsub(" ", "-", level2)) %>%
  dplyr::group_by(category, subcategory) %>% 
  dplyr::summarise(sales = n() ^ 3 ) %>% 
  dplyr::ungroup() %>% 
  dplyr::sample_n(31)

highcharter::hctreemap2(dfitemsg, 
              group_vars = c("category"),
              size_var = "sales", 
              color_var = "sales",
              layoutAlgorithm = "squarified",
              levelIsConstant = FALSE,
              allowDrillToNode = TRUE,
              palette = rev(viridis(6))) %>% 
  hc_add_theme(thm)
```

### Best Sellers

```{r barchart}
set.seed(2)
nprods <- 10
dfitems %>% 
    # this is the previous data 
    dplyr::sample_n(nprods) %>% 
    # pull this variable out as a vector
    .$labels %>% 
    # this repeats 
    rep(times = sort(sample(x = 1e4:2e4, 
                            size = nprods), 
                     decreasing = TRUE)) %>% 
    # convert to a factor
    base::factor(levels = unique(.)) %>%
    # utils::str()
    # add the chart
    highcharter::hchart(showInLegend = FALSE, 
           name = "Sales", 
           pointWidth = 10) %>% 
    # we created this above
    highcharter::hc_add_theme(thm) %>% 
    # convert this to a bar
    highcharter::hc_chart(type = "bar")
```
