---
title: 'Shinydashboard for cannabis data'
author: "Martin Frigaard"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
# create figs folder ----
if (!file.exists("figs/")) {
    dir.create("figs/")
}
# create data folder ----
if (!file.exists("data/")) {
    dir.create("data/")
}
# create docs folder ----
if (!file.exists("docs/")) {
    dir.create("docs/")
}
library(knitr)
library(rmdformats)
library(tidyverse)
library(devtools)
library(hrbrthemes)
library(inspectdf)
# chunks set options
knitr::opts_chunk$set(
  echo = TRUE, # show/hide all code
  # results = "hide", # hide results
  tidy = FALSE, # cleaner code printing
  comment = "#> ", # better console printing
  eval = TRUE, # turn this to FALSE stop code chunks from running
  message = TRUE, # show messages
  warning = FALSE, # show warnings
  size = "small", # size of the text
  fig.path = "figs/", # location of files
  fig.height = 5.5, # height of figures
  fig.width = 8 # width of figures
) # width of figures
# knit set options
knitr::opts_knit$set(
  width = 78,
  progress = FALSE
)
# base options
base::options(
  tibble.print_max = 25,
  tibble.width = 78,
   max.print = 999999,
  scipen = 100000000
)
```


# Motivation 

Document the app for Cannibus data. 

## bloomfilter script

```{r bloomfilter.R, message=FALSE, warning=FALSE}
source("bloomfilter.R")
ls()
```

```{r global-r, message=FALSE}
source("global.R")
ls()
```

## Import the `cranlog` data object 

This will give us some data to play with. 

```{r CranLog}
# fs::dir_ls("data")
CranLog <- readr::read_csv("data/cranlog.csv") %>% 
    dplyr::select(-c(X1))
CranLog %>% dplyr::glimpse(78)
```

## Bubbles plot

We can replace the `pkgData()` with `CranLog` in the code below:

```{r bubbles-plot-in-app, eval=FALSE}
    order <- unique(pkgData()$package)
    
    df <- pkgData() %>%
        
      group_by(package) %>%
        
      tally() %>%
        
      arrange(desc(n), tolower(package)) %>%
        
      # Just show the top 60, otherwise it gets hard to see
      head(60)

    bubbles(df$n, df$package, key = df$package)
```


```{r bubbles}
# sort the CranLog by package
order <- unique(CranLog$package)

df <- CranLog %>%
      # df is grouped by package and...
      dplyr::group_by(package) %>%
      # tallied
      dplyr::tally() %>%
      # then arranged in descending order
      dplyr::arrange(desc(n), 
                     # then lower case all package chars
                     stringr::str_to_lower(package)) %>%
      # Just show the top 60, otherwise it gets hard to see
      utils::head(50)

bubbles::bubbles(value = df$n, 
        label = df$package, 
        key = df$package, 
        textColor = c("black"))
```


