---
title: "Old Faithful Eruptions -example"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(datasets)
library(ggplot2)
library(tidyverse)
data(faithful)
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("n_breaks", 
            label = "Number of bins:",
            choices = c(10, 20, 35, 50), 
            selected = 20)

sliderInput("alpha_adjust", 
            label = "Alpha adjustment:",
            min = 0.2, 
            max = 2, 
            value = 1, 
            step = 0.2)
```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
    # plot with ggplot2
    ggplot2::ggplot(faithful, aes(x = eruptions)) + 
        # add bins 
        geom_histogram(bins = as.numeric(input$n_breaks),
                       alpha = as.numeric(input$alpha_adjust)) + 
        # add labels 
        ggplot2::labs(x = "Duration (minutes)",
                      title = "Geyser Eruption Duration")
    
  # hist(faithful$eruptions, 
  #      probability = TRUE, 
  #      breaks = as.numeric(input$n_breaks),
       # xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
  # dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  # lines(dens, col = "blue")
})
```
